
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: open5gs
  name: open5gs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs
  template:
    metadata:
      labels:
        app: open5gs
    spec:
      hostname: epc
#      hostNetwork: true
      containers:
      - image: vcore-mme
        name: vcore-mme-container
        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 1000-55000
#          protocol:
#          - TCP
#          - UDP
#          - SCTP
#        command: ['/bin/sh', '/docker-entrypoint/run.sh']
#        command: ['/bin/sh', '/docker-entrypoint/deploy-test.sh']
#        ports:

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true