
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: open5gs
  name: open5gs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: open5gs
    spec:
      containers:
      - image: e2e-network
        name: open5gs-container
        imagePullPolicy: Never
#        command: ["/bin/sleep", "3650d"]
#        resources: {}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true