apiVersion: apps/v1
kind: pod
metadata:
  name: epc-deployment
  labels:
    app: epc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epc
  template:
    metadata:
      labels:
        app: epc
    spec:
      containers:
        - name: cepc
#          image: e2e-network:latest
          image: debian:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
#            privileged: true         
