apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 3
#  strategy: 
#    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: vcore-mme
#        image: nginx
        imagePullPolicy: IfNotPresent
#        command: ['sh', '-c']        
#        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
#        resources: {}
#        command: ['sh', './run.sh']
#        command: ["/bin/bash"]
#        args: ["/bin/sh", "-c", "while true; do echo hello; sleep 10;done"]
#        command: ['/bin/sh', './docker-entrypoint/run.sh']
        securityContext:
#          capabilities:
#            add:
#              - NET_ADMIN
          privileged: true